Home screen
JonasImm/pryces pull request #69
Opened 2020-10-03 16:42 UTC by JonasImm

2020-10-04 11:07 UTC, jamarob requested changes
Hi Jonas,
left my 2 cents, mostly on naming and some possible simplifications. Please use semantic tags where appropriate. 

You define a lot of states in your components, maybe hide some of the complexity in a custom hook? 

https://github.com/JonasImm/pryces/blob/44a334007a4a6db13c9f094521de8970a12070d0/client/src/pages/List.js#L39

This **needs** to be changed, don't generate ids with `Math.random()`!! Returning the same number on consecutive calls is _perfectly fine_ for a random generator. Use a package like uuid instead.

2020-10-04 11:07 UTC, jamarob commented on client/src/components/EmptyListScreen.js
> +EmptyListScreen.propTypes = {
I like to keep PropTypes near the start of the component function where they are destructured for quick reference what is what.

2020-10-04 11:07 UTC, jamarob commented on client/src/components/EmptyListScreen.js
>        <div>
Why the inner div?

2020-10-04 11:07 UTC, jamarob commented on client/src/components/EmptyListScreen.js
>  export default EmptyListScreen;
Exporting the function where it is defined is prefered imho.

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
>    const [inputfield, setInputfield] = useState(false);
Maybe camel case like `inputField`?

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
> +    function handleLists() {
Why the wrapper, seems unnecessary?

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
>      await refetch();
Post and refetch seems like an extra roundtrip to the server, is this really necessary to keep your data in sync?

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
> +        {userLists?.length < 1 && (
userLists is initialized to null, which is falsy so simply do `usersList && ...` Think about turning this and the next check into a ternary.

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
> +        {userLists?.length > 0 && (
Initializing `userLists` to an empty array will save you the optional chaining. Array length greater 0 are truthy, simplify to just `userLists.length && ..`. See comment above.

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
> +              {error && <div>Could not get data. Please cry.</div>}
Semantic tags ;)

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/Home.js
>            <ListCreationContainer
ListCreationContainer sounds like a form.

2020-10-04 11:07 UTC, jamarob commented on client/src/pages/List.js
> +            {list.products?.length < 1 && (
Simplyfiy your conditionals and maybe turn this into a ternary, as they are complements of each other.

2020-10-05 08:20 UTC, JonasImm commented on client/src/components/EmptyListScreen.js
>        <div>
For styling purpose

2020-10-05 08:21 UTC, JonasImm commented on client/src/components/EmptyListScreen.js
>  export default EmptyListScreen;
This is the convention we learned and as this is implemented in all my projects for now. Will keep it mind 👍

2020-10-05 08:23 UTC, JonasImm commented on client/src/pages/Home.js
> +    function handleLists() {
Which wrapper? the useEffect?

2020-10-05 08:24 UTC, JonasImm commented on client/src/pages/Home.js
>      await refetch();
Otherwise my data will not be visible on each post

2020-10-05 08:25 UTC, jamarob commented on client/src/components/EmptyListScreen.js
>  export default EmptyListScreen;
Just my preference ;)

2020-10-05 08:30 UTC, JonasImm commented on client/src/pages/Home.js
> +        {userLists?.length < 1 && (
Good point, but I will then have a slight moment of where my empty list container is visible

2020-10-05 08:36 UTC, JonasImm commented on client/src/pages/Home.js
> +        {userLists?.length > 0 && (
For now, I will stick to my method. But I will keep yours in mind. I think I tried it before without success

2020-10-05 08:36 UTC, JonasImm commented on client/src/pages/Home.js
> +              {error && <div>Could not get data. Please cry.</div>}
👍

2020-10-05 08:37 UTC, JonasImm commented on client/src/pages/Home.js
>            <ListCreationContainer
That's because it is a form ;)

2020-10-05 08:37 UTC, JonasImm commented on client/src/pages/List.js
> +            {list.products?.length < 1 && (
see comment above

2020-10-05 08:47 UTC, merged